[build]
  command = "npm install && npm run build"
  publish = "client/dist"

[context.production.environment]
  NODE_VERSION = "16.x"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "https://react-devfolio-2b1f0a2540a0.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
